name: "Sensenet Tests"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  sensenet-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
    env:
        TF_CPP_MIN_LOG_LEVEL: 2

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install test dependencies
      run: |
        pip install pytest
        pip install "scikit-learn>=1.0,<1.1"

    - name: Install sensenet
      run: |
        pip install .

    - name: Run sensenet tests
      run: |
        pytest -sv
